### ISSUE TITLE
Update issue template?

### ISSUE THREAD

**Issue by monicagerber** [getwilds/.github#3]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask in the Fred Hutch Data Slack <https://hutchdatascience.org/joinslack/> or email us at <wilds@fredhutch.org>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) start by reading <https://www.tidyverse.org/help/#reprex>

Brief description of the problem: I see this alert when I pull up the issue template. 
<img width="915" alt="Screenshot 2024-04-11 at 11 10 10 AM" src="https://github.com/getwilds/.github/assets/4185874/c215afcf-5e44-47e7-a25a-04facc940ad9">

**Comment by sckott** [comment]
Ooof, sorry I totally missed this - I guess when I was on leave.

**Comment by sckott** [comment]
done!
